CREATE DATABASE IF NOT EXISTS mqaf CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'mqaf'@'%' IDENTIFIED BY 'mqaf';
GRANT ALL PRIVILEGES ON *.* TO 'mqaf'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
